=== canwe/Handling-State/handling state processor/src/dp/test/xml/xsd/order.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="shiporder">
	  <xs:complexType>
	    <xs:sequence>
	    	<!-- Default value for minOccurs and maxOccurs is 1 -->
	    	<xs:element name="orderperson" type="xs:string"/>
	    	<xs:element name="start" type="xs:date"/>
	    	<xs:element name="shipto">
			  <xs:complexType>
			    <xs:sequence>
			      <xs:element name="name" type="xs:string"/>
			      <xs:element name="address" type="xs:string"/>
			      <xs:element name="city" type="xs:string"/>
			      <xs:element name="country" type="xs:string"/>
			    </xs:sequence>
			  </xs:complexType>
			</xs:element>
			<xs:element name="item" maxOccurs="unbounded"><!-- any number of items more than 0 -->
			  <xs:complexType>
			    <xs:sequence>
			      <xs:element name="title" type="xs:string"/>
			      <xs:element name="note" type="xs:normalizedString" minOccurs="0"/><!-- Optional -->
			      <xs:element name="quantity" type="xs:positiveInteger"/>
			      <xs:element name="price" type="xs:decimal"/>
			    </xs:sequence>
			  </xs:complexType>
			</xs:element>
	    </xs:sequence>
	    <!-- Attributes must come last! -->
	    <xs:attribute name="orderid" type="xs:string" use="required"/>
	  </xs:complexType>
	</xs:element>
</xs:schema>

=== canwe/Handling-State/handling state processor/src/dp/test/xml/xsd/order.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<shiporder orderid="889923"
		   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="order.xsd">
  <orderperson>John Smith</orderperson>
  <start>2011-02-14</start>
  <shipto>
    <name>Sherlock Holmes</name>
    <address>221b, Baker Str</address>
    <city>London NW1 6XE</city>
    <country>UK</country>
  </shipto>
  <item>
    <title>Smoking pipe</title>
    <note>Special Edition</note>
    <quantity>1</quantity>
    <price>10.90</price>
  </item>
  <item>
    <title>Violin</title>
    <quantity>1</quantity>
    <price>99.99</price>
  </item>
</shiporder>
